# # Install pre-commit hooks via
# pre-commit install

# modernizer: make sure our code-base is Python 3 ready
repos:
- repo: https://github.com/python-modernize/python-modernize.git
  rev: a234ce4e185cf77a55632888f1811d83b4ad9ef2
  hooks:
  - id: python-modernize
    types: [python]
    args:
      - --write
      - --nobackups

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.4
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format